name: smok_pomaga
description: "SmokPomaga - Aplikacja do znajdowania i zarządzania wydarzeniami wolontarskymi."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Date formatting
  intl: ^0.19.0
  
  # UUID generation
  uuid: ^4.5.1
  
  # Navigation
  go_router: ^14.6.2
  
  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation for Isar
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12
  
  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/logo.png
    - assets/images/mlody_krakow_vertical.png
    - assets/images/mlody_krakow_horizontal.png
